language: vim

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    packages:
    - g++-4.7
    - cmake

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script: |
  vim -Nu 'test/.vimrc' -c 'Vader! test/cmake.vader'
